git:
  ignoreWhitespaceInDiffView: true
  autoStageResolvedConflicts: false
  log:
    order: default
promptToReturnFromSubprocess: false

keybinding:
  universal:
    toggleWhitespaceInDiffView: "ctrl+tab"
