# Generated by omarchy-theme-set-templates from the Omarchy theme's colors.toml.
# Source: ~/.config/omarchy/themed/zsh_vi_colors.zsh.tpl (chezmoi-managed).
#
# zsh-vi-mode visual-selection highlight: the theme's magenta (color5) blended
# 47% into the theme background, matching arrowlake.nvim's IncSearch/Substitute
# color (#d7a9b1 for the light theme).
ZVM_VI_HIGHLIGHT_FOREGROUND='{{ foreground }}'
ZVM_VI_HIGHLIGHT_BACKGROUND='{{ mix background color5 47% }}'
