workspace = name:special:yazi,on-created-empty:omarchy-launch-or-focus-tui yazi
workspace = name:special:notes,on-created-empty:uwsm-app -- xdg-terminal-exec --dir="$HOME/Documents/notes" --command nvim
workspace = name:special:activity,on-created-empty:omarchy-launch-tui btop
workspace = name:special:icloud,on-created-empty:omarchy-launch-webapp "https://www.icloud.com/"
workspace = name:special:music,on-created-empty:omarchy-launch-webapp "https://music.apple.com"
workspace = name:special:youtube,on-created-empty:omarchy-launch-webapp "https://youtube.com/"
workspace = name:special:discord,on-created-empty:vesktop
workspace = name:special:keyboard,on-created-empty:omarchy-launch-webapp "https://my.moergo.com/go60/##/" && omarchy-launch-webapp "https://my.moergo.com/glove80/##/", layout:scrolling, layoutopt:direction:up

workspace = name:special:scratch, layout:scrolling, layoutopt:direction:right

