workspace = name:special:yazi,on-created-empty:omarchy-launch-tui yazi
workspace = name:special:activity,on-created-empty:omarchy-launch-tui btop
workspace = name:special:youtube,on-created-empty:omarchy-launch-webapp "https://youtube.com/"
workspace = name:special:keyboard,on-created-empty:omarchy-launch-webapp "https://my.moergo.com/go60/##/" && omarchy-launch-webapp "https://my.moergo.com/glove80/##/", layout:scrolling, layoutopt:direction:up

workspace = name:special:scratch,on-created-empty:uwsm-app -- xdg-terminal-exec --dir="$HOME/Documents/notes" --command nvim, layout:scrolling, layoutopt:direction:right

workspace = name:special:media, on-created-empty:omarchy-launch-webapp "https://www.icloud.com/"  && omarchy-launch-webapp "https://www.reddit.com/" && omarchy-launch-webapp "https://music.apple.com" && vesktop, layout:scrolling, layoutopt:direction:right
