[preview]
tab_size = 4
image_delay = 5
image_filter = "triangle"
image_quality = 75
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[[plugin.prepend_fetchers]]
group = ""
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
group = ""
id = "git"
url = "*/"
run = "git"
