# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser
$hypr_scripts = /home/jadon/.config/hypr/scripts

unbind = SUPER, W
unbind = SUPER ALT, SPACE
unbind = SUPER CTRL, TAB
unbind = SUPER ALT, TAB
unbind = SUPER, TAB

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, E, File manager, exec, $hypr_scripts/nautilus-ctrl-t.sh
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER ALT, B, Browser (private), exec, $browser --private
bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, uwsm app -- gnome-system-monitor
bindd = SUPER SHIFT, D, Docker, exec, $terminal -e lazydocker
bindd = SUPER SHIFT, G, Gamemode, exec, $hypr_scripts/gamemode.sh
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER, slash, Passwords, exec, uwsm app -- 1password

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER ALT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, A, Claude, exec, omarchy-launch-webapp "https://claude.ai"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://calendar.google.com/calendar/"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://mail.google.com/mail/"
bindd = SUPER, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"

# Overwrite existing bindings, like putting Omarchy Menu on Super
bindd = SUPER, Q, exec, killactive
binddr = SUPER, SUPER_L, Omarchy menu, exec, pkill walker || omarchy-menu
bindd = SUPER, TAB, Former workspace, workspace, previous
bindd = SUPER, COMMA, Previous workspace, workspace, e-1
bindd = SUPER, PERIOD, Next workspace, workspace, e+1


# utilities
bind = SUPER, A, exec, $hypr_scripts/smart-select.sh
unbind = SUPER, C
bindd = SUPER, C, Copy, exec, $hypr_scripts/smart-copy.sh
bindd = SUPER, Z, Ctrl Z, sendshortcut, CTRL, Z,
