# From omarchy windows.conf as of 10/5/25
windowrule = suppressevent maximize, class:.*
windowrule = opacity 0.97 0.9, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
source = ~/.config/hypr/apps.conf
#

# My changes
windowrule = opacity 0.97 0.93, tag:chromium-based-browser

# Per app styling
windowrule = opacity 0.8 0.7 override, class:org.gnome.SystemMonitor
windowrule = opacity 0.85 0.7 override, class:org.gnome.Nautilus.*

windowrule = opacity 1 1 override, class:gnome-system-monitor

windowrule = float, class:com.omarchy.Omarchy
windowrule = center, class:com.omarchy.Omarchy
windowrule = size 1100 945, class:com.omarchy.Omarchy

windowrule = float, class:com.omarchy.Impala
windowrule = center, class:com.omarchy.Impala
windowrule = stayfocused, class:com.omarchy.Impala
windowrule = size 1650 1000, class:com.omarchy.Impala

windowrule = float, class:com.omarchy.Wiremix
windowrule = center, class:com.omarchy.Wiremix 
windowrule = stayfocused, class:com.omarchy.Wiremix 
windowrule = size 920 600, class:com.omarchy.Wiremix 

windowrule = float, class:blueberry.py
windowrule = center, class:blueberry.py
# windowrule = stayfocused, class:blueberry.py
windowrule = size 600 700, class:blueberry.py

# Steam
windowrule = opacity 1 1, class:steam
windowrule = float, class:steam, title:Friends List
windowrule = center, class:steam, title:Friends List
windowrule = idleinhibit fullscreen, class:steam
windowrule = opacity 1 1, class:.*[Ss]team.*
windowrule = fullscreen, class:.*steam_app.*

# Else
windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 1400 900, tag:floating-window

windowrule = tag +floating-window, class:(blueberry.py|org.gnome.SystemMonitor|gnome-system-monitor|com.gabm.satty|About|TUI.float|org.gnome.Nautilus.*)
windowrule = tag +floating-window, class:(xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus), title:^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files)

windowrule = fullscreen, class:Screensaver

windowrule = opacity 1 1, class:^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$
