# My changes
windowrule = opacity 0.87 0.83, tag:chromium-based-browser

# Per app styling
windowrule = opacity 0.85 0.7 override, class:org.gnome.Nautilus.*


windowrule = float, class:org.gnome.Nautilus.*
windowrule = center, class:org.gnome.Nautilus.*
windowrule = size 1100 700, class:org.gnome.Nautilus.*

windowrule = float, class:text.box
windowrule = center, class:text.box
windowrule = size 40% 40%, class:text.box
