# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "4" }

# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "3", italic = true }
find_position = { fg = "1", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "2", bg = "2" }
marker_copied = { fg = "3", bg = "3" }
marker_cut = { fg = "1", bg = "1" }

# Tab
tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

# Border
border_symbol = "│"
border_style = { fg = "8" }

# Highlighting
syntect_theme = "~/.config/yazi/rose-pine.tmTheme"

# : }}}

# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "0", bg = "2" }

# Mode
mode_normal = { fg = "0", bg = "6", bold = true }
mode_select = { fg = "15", bg = "2", bold = true }
mode_unset = { fg = "15", bg = "1", bold = true }

# Progress
progress_label = { fg = "15", bold = true }
progress_normal = { fg = "0", bg = "0" }
progress_error = { fg = "1", bg = "0" }

# Permissions BROKEN!!!
permissions_t = { fg = "2" }
permissions_r = { fg = "3" }
permissions_w = { fg = "1" }
permissions_x = { fg = "4" }
permissions_s = { fg = "8" }

# : }}}


# : Input {{{

[input]
border = { fg = "8" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border = { fg = "8" }
active = { fg = "1" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "8" }
title = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "0" }
cand = { fg = "4" }
rest = { fg = "7" }
desc = { fg = "1" }
separator = "  "
separator_style = { fg = "8" }

# : }}}


# : Help {{{

[help]
on = { fg = "1" }
exec = { fg = "4" }
desc = { fg = "7" }
hovered = { bg = "8", bold = true }
footer = { fg = "0", bg = "15" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "2" },

    # Videos
    { mime = "video/*", fg = "3" },
    { mime = "audio/*", fg = "3" },

    # Archives
    { mime = "application/zip", fg = "1" },
    { mime = "application/gzip", fg = "1" },
    { mime = "application/x-tar", fg = "1" },
    { mime = "application/x-bzip", fg = "1" },
    { mime = "application/x-bzip2", fg = "1" },
    { mime = "application/x-7z-compressed", fg = "1" },
    { mime = "application/x-rar", fg = "1" },

    # Fallback
    { name = "*", fg = "5" },
    { name = "*/", fg = "4" },
]

# : }}}
