accent = "#8577D4"
cursor = "#54473f"
foreground = "#54473f"
background = "#ebe0cf"
selection_foreground = "#54473f"
selection_background = "#d6dfcd"

color0 = "#bcb3a6"
color1 = "#bf4b5f"
color2 = "#24755f"
color3 = "#bc8d32"
color4 = "#6486B5"
color5 = "#B377D4"
color6 = "#65aca6"
color7 = "#87786c"
color8 = "#72675f"
color9 = "#e73d61"
color10 = "#008569"
color11 = "#d19900"
color12 = "#5894da"
color13 = "#c77fed"
color14 = "#4cbeb6"
color15 = "#54473f"
