accent = "#a96fd1"
cursor = "#54473f"
foreground = "#54473f"
background = "#ebe0cf"
selection_foreground = "#54473f"
selection_background = "#d6dfcd"

color0 = "#bcb3a6"
color1 = "#bf4b5f"
color2 = "#467e60"
color3 = "#bc8d32"
color4 = "#897bd8"
color5 = "#a96fd1"
color6 = "#65aca6"
color7 = "#87786c"
color8 = "#72675f"
color9 = "#e73d61"
color10 = "#358f64"
color11 = "#d19900"
color12 = "#9686f2"
color13 = "#bd76ec"
color14 = "#4cbeb6"
color15 = "#54473f"
