accent = "#b784d8"
cursor = "#40362f"
foreground = "#40362f"
background = "#f4ecde"
selection_foreground = "#40362f"
selection_background = "#dce7d7"

color0 = "#c3bdb2"
color1 = "#cf6781"
color2 = "#5a947a"
color3 = "#d8ac4f"
color4 = "#897bd8"
color5 = "#b784d8"
color6 = "#84cbc4"
color7 = "#918579"
color8 = "#7b726b"
color9 = "#e66e8d"
color10 = "#49a680"
color11 = "#f0b800"
color12 = "#9686f2"
color13 = "#c98eef"
color14 = "#6cded4"
color15 = "#40362f"
