$base      = rgba(7b726bff) # Matches #7b726b
$text      = rgba(40362fff) # Matches #40362f
$cyan      = rgba(8cc6c2ff) # Cyan #8cc6c2
$red       = rgba(cf6f8bff) # Red #cf6f8b
$surface   = rgba(40362fff) # Border #40362f
$blue      = rgba(8b83cfff) #Blue #8b83cf
$magenta   = rgba(b18bcfff) #Magenta #b18bcf
$yellow    = rgba(d0aa5bff) #Yellow #d0aa5b
