$base      = rgba(7b726bff) # Matches #7b726b
$text      = rgba(40362fff) # Matches #40362f
$cyan      = rgba(84cbc4ff) # Cyan #84cbc4
$red       = rgba(d66f8eff) # Red #d66f8e
$surface   = rgba(40362fff) # Border #40362f
$blue      = rgba(897bd8ff) #Blue #897bd8
$magenta   = rgba(b784d8ff) #Magenta #b784d8
$yellow    = rgba(d8ac4fff) #Yellow #d8ac4f
