$base      = rgba(ad9b88ff) # Matches #ad9b88
$text      = rgba(54473fff) # Matches #54473f
$cyan      = rgba(4ba08dff) # Cyan #4ba08d
$red       = rgba(bf4b5fff) # Red #bf4b5f
$surface   = rgba(54473fff) # Border #54473f
$blue      = rgba(6486B5ff) #Blue #6486B5
$magenta   = rgba(B59364ff) #Yellow #B59364
$yellow    = rgba(C97599ff) #Magenta #C97599
