$base      = rgba(312e55ff)  # Matches #312e55
$text      = rgba(c8d3f5ff) # Matches #c8d3f5
$cyan      = rgba(58e2cbff) # Cyan #58E2CB
$red       = rgba(ff007cff) # Red #ff007c
$surface   = rgba(c8d3f5ff) # Border #c8d3f5
$blue      = rgba(3f3bf5ff) #Blue #3F3BF5
$magenta   = rgba(c24ebaff) #Magenta #C24EBA
$yellow    = rgba(ffd888ff) #Yellow #FFD888
