$base      = rgba(312e55ff)  # Matches #312e55
$text      = rgba(bec8e8ff) # Matches #bec8e8
$cyan      = rgba(33D4B4ff) # Cyan #33D4B4
$red       = rgba(E50050ff) # Red #E50050
$surface   = rgba(bec8e8ff) # Border #bec8e8
$blue      = rgba(3f3bf5ff) #Blue #3F3BF5
$magenta   = rgba(D91C87ff) #Magenta #D91C87
$yellow    = rgba(ffd888ff) #Yellow #FFD888
